<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Coupon extends Seeder
{
    public function run()
    {
        DB::table('coupons')->insert([
            [
                'company' => 'Tato ProMusic',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '10% de descuento en arreglos de instrumentos acústicos entre $30.000 y $160.000',
                'discount' => '10',
                'points' => 320,
                'phone' => '3215134624',
                'address' => 'Carr 4 C sur #2-93 - San Benito',
                'image' => 'Tato%20ProMusic.jpg',
            ],
            [
                'company' => 'Tato ProMusic',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '15% de descuento por compras de instrumentos entre $160.000 y $600.000',
                'discount' => '15',
                'points' => 1800,
                'phone' => '3215134624',
                'address' => 'Carr 4 C sur #2-93 - San Benito',
                'image' => 'Tato%20ProMusic.jpg',
            ],
            [
                'company' => 'NefertumTuaroma',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '10% de descuento por compras entre $30.000 y $120.000',
                'discount' => '10',
                'points' => 240,
                'phone' => '3202631978',
                'address' => 'Calle 8 n° 4-116, Barrio Versalles',
                'image' => 'NefertumTuaroma.png',
            ],
            [
                'company' => 'Te&Seg',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '15% de descuento por compras entre $80.000 y $160.000',
                'discount' => '15',
                'points' => 480,
                'phone' => '3202164680',
                'address' => 'Carrera 3 # 7-58 Centro',
                'image' => 'Te&Seg.png',
            ],
            [
                'company' => 'Taqueria los compadres',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '20% de descuento por compras entre $30.000 y $100.000',
                'discount' => '20',
                'points' => 400,
                'phone' => '3106771733',
                'address' => 'Taqueria Calle 8 #7a - 19 Facatativá',
                'image' => 'La%20taqueria%20-%20los%20compadres.jpg',
            ],
            [
                'company' => 'Chocofrut',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '2x1 en uvas achocolatadas tradicionales de 15.000',
                'discount' => '50',
                'points' => 300,
                'phone' => '3138475766',
                'address' => 'Tienda Virtual: @chocofrut__col',
                'image' => 'ChocoFrut.jpg',
            ],
            [
                'company' => 'Restaurante Berlin',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '25% de descuento por compras entre $14.000 y $25.000',
                'discount' => '25',
                'points' => 125,
                'phone' => '3137206955',
                'address' => 'Calle 15#15-24 Berlin',
                'image' => 'Restaurante%20berlin.jpg',
            ],
            [
                'company' => 'Centauros Voleiboll',
                'stock' => 150,
                'stock_inicial' => 150,
                'description' => '1 dia de entrenamiento completamente gratis',
                'discount' => '100',
                'points' => 200,
                'phone' => '3134409390',
                'address' => 'Polideportivo la esmeralda',
                'image' => 'CentaurosVoley.jpg',
            ],
            [
                'company' => 'Centauros Voleiboll',
                'stock' => 50,
                'stock_inicial' => 50,
                'description' => '20% de descuento en tu mensualidad.',
                'discount' => '20',
                'points' => 320,
                'phone' => '3134409390',
                'address' => 'Polideportivo la esmeralda',
                'image' => 'CentaurosVoley.jpg',
            ],
            [
                'company' => 'Centauros Baloncesto',
                'stock' => 150,
                'stock_inicial' => 150,
                'description' => '1 dia de entrenamiento completamente gratis',
                'discount' => '100',
                'points' => 200,
                'phone' => '3134409390',
                'address' => 'Polideportivo la esmeralda',
                'image' => 'Centauros%20Basket.jpg',
            ],
            [
                'company' => 'Centauros Baloncesto',
                'stock' => 50,
                'stock_inicial' => 50,
                'description' => '20% de descuento en tu mensualidad.',
                'discount' => '20',
                'points' => 320,
                'phone' => '3134409390',
                'address' => 'Polideportivo la esmeralda',
                'image' => 'Centauros%20Basket.jpg',
            ],
            [
                'company' => 'StreetCrown',
                'stock' => 200,
                'stock_inicial' => 200,
                'description' => '20% de descuento por compras entre 60.000 y 200.000',
                'discount' => '20',
                'points' => 400,
                'phone' => '3164987412',
                'address' => 'Tienda Virtual: @street__crown',
                'image' => 'StreetCrown.jpg',
            ],
            [
                'company' => 'Pasos de moda',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '15% de descuento por compras entre $300.000 y $500.000',
                'discount' => '15',
                'points' => 1000,
                'phone' => '3014625480',
                'address' => 'Carrera 3 #3-68 local croydon',
                'image' => 'Pasos%20de%20moda.jpg',
            ],
            [
                'company' => 'Pasos de moda',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '20% de descuento en tu segundo par de tennis',
                'discount' => '20',
                'points' => 800,
                'phone' => '3014625480',
                'address' => 'Carrera 3 #3-68 local croydon',
                'image' => 'Pasos%20de%20moda.jpg',
            ],
            [
                'company' => 'Pepperoni',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '10% de descuento por compras entre $50.000 y $150.000',
                'discount' => '10',
                'points' => 300,
                'phone' => '3054426202',
                'address' => 'Cra 5 #13-00 laureles',
                'image' => 'Peperoni.jpg',
            ],
            [
                'company' => 'Pepperoni',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => 'Por compras superiores a 100.000 mil recibe la bebida (1.5 litros) gratis',
                'discount' => '100',
                'points' => 240,
                'phone' => '3054426202',
                'address' => 'Cra 5 #13-00 laureles',
                'image' => 'Peperoni.jpg',
            ],
            [
                'company' => 'Bendita tentacion',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '15% de descuento por compras entre $50.000 y $70.000',
                'discount' => '15',
                'points' => 210,
                'phone' => '3203201482',
                'address' => 'Calle 11 #5-14 Facatativá',
                'image' => 'Bendita%20tentacion.jpg',
            ],
            [
                'company' => 'Bendita tentacion',
                'stock' => 100,
                'stock_inicial' => 100,
                'description' => '10 % de descuento por compras entre $35.000 y $50.000',
                'discount' => '10',
                'points' => 100,
                'phone' => '3203201482',
                'address' => 'Calle 11 #5-14 Facatativá',
                'image' => 'Bendita%20tentacion.jpg',
            ],
        ]);
    }
}